group:
  - repos: |
      nourishd/nourishd
    files:
      - source: files/.github/dependabot.yml
        dest: .github/dependabot.yml
      - source: files/.github/workflows/dependabot-auto-merge.yml
        dest: .github/workflows/dependabot-auto-merge.yml
      - source: files/.editorconfig
        dest: .editorconfig
      - source: files/.gitattributes
        dest: .gitattributes
      - source: files/pint.json
        dest: pint.json
